### PR TITLE
Added new character - Meliodas

### PR DESCRIPTION
**Pull request by sidhartha2002**
I have added a new character in **gif format** . Kindly review it by accepting my pull request.

### CODE REVIEW

**Comment by Satyasuranjeet** [comment]
Actually, you made a mistake with the branching that resulted in a conflict, making it not possible to me to include your request into my code. Therefore, before pulling a request, please modify the code.

Thank you.

**Comment by sidhartha2002** [comment]
Bro, I couldn't get you.
When I was about to contribute to your repository for the second time I saw that my cloned repository is _25 commits behind your original repo_. Then I clicked the **sync fork** option which made my repo updated with the original repository. But to assure myself, I cross checked my forked repository by running in live server.
Then I made the changes and simply made a pull request.

Kindly recommend me where am I wrong and what to do to make it correct.

Thanks.

**Comment by Satyasuranjeet** [comment]
Just one thing, please clone the Letest repository, modify the file with your code, and then submit a pull request. Check the branch you are pushing to before you do so.

**Comment by sidhartha2002** [comment]
ok! thanks

**Pull request closed without merging**
