### PR TITLE
Added a new Anime Character Card

### PR DESCRIPTION
**Pull request by aysh2603**

### CODE REVIEW

**Review by Satyasuranjeet — COMMENTED** [review]
CHARACTER YUJI ITADORI ADDED

**Comment by aysh2603** [comment]
> CHARACTER YUJI ITADORI ADDED

Is the PR merged?
Did I do the push correctly?

**Comment by Satyasuranjeet** [comment]
No just give me some time to do that 😊

**Comment by aysh2603** [comment]
I am a contributor in hackodex. Will I get points on this PR?

**Comment by Satyasuranjeet** [comment]
Yes, it is.

**Comment by aysh2603** [comment]
Please add hackodex2023-accepted label in the merged PR.

**Comment by Satyasuranjeet** [comment]
Already added

**Comment by aysh2603** [comment]
It is not showing. Can you please check it again?

**Comment by Satyasuranjeet** [comment]
[image: image.png]
you can see .

**Comment by Satyasuranjeet** [comment]
is it showing now please conform

**Pull request merged**
